version: '3.4'

services:
  web:
    image: img-static-site-example
    build: 
      context: .
      dockerfile: UI\Dockerfile
    container_name: map-client
    depends_on: 
      - emergencyroadsideassistance
    restart: always
    ports:
      - "8200:80"

  emergencyroadsideassistance:
    image: ${DOCKER_REGISTRY-}emergencyroadsideassistance
    build:
      context: .
      dockerfile: EmergencyRoadsideAssistance\Dockerfile
    ports:
      - 8080:80
    depends_on: 
      - db
    environment:
        httpPort: 80
        launchUrl: "{Scheme}://{ServiceHost}:{ServicePort}/swagger"
        publishAllPorts: true

  db:
    image: stellirin/postgres-windows
    restart: always
    ports:
      - 15432:5432
    environment:
        POSTGRES_USER: era
        POSTGRES_PASSWORD: password
    volumes:
      - .\EmergencyRoadsideAssistance\docker-entrypoint-initdb:C:\docker-entrypoint-initdb.d